### PR TITLE
[Analytics][l]: #238 Add support for plausible, simpleanalytics, Google, PostHog analytics 

### PR DESCRIPTION
**Pull request by mohamedsalem401**
For https://github.com/datopian/flowershow/issues/238

1. The configuration for analytics would be something like: `config.mjs`
```js
    analyticsConfig: {
        plausibleAnalytics: {
            plausibleDataDomain: 'tailwind-nextjs-starter-blog.vercel.app',
        },
        simpleAnalytics: {
            src: "https://scripts.simpleanalyticscdn.com/latest.js"
        },
        umamiAnalytics: {
            umamiWebsiteId: '123e4567-e89b-12d3-a456-426614174000',
        },
        posthogAnalytics: {
            posthogProjectApiKey: '123e4567-e89b-12d3-a456-426614174000',
        },
        googleAnalytics: {
            googleAnalyticsId: 'G-XXXXXXX', // e.g. G-XXXXXXX
        },
    }
```
2. The user can add more than a single analytics at the same time
3. Old analytics for users would work just fine
4. No documentation has been updated yet

### CODE REVIEW

**Comment by rufuspollock** [comment]
@mohamedsalem401 did you follow pliny here? Could we even directly *reuse* pliny via importing their modules?

**Comment by rufuspollock** [comment]
@mohamedsalem401 also shouldn't these changes be upstream in the core repo i.e. https://github.com/datopian/portaljs/tree/main/packages/core/src

We want stuff in a core library and then we just import the parts we want in the template (in a perfect world we only import something if we use it)

**Comment by mohamedsalem401** [comment]
@Rufus, as per your suggestion, I managed to find the npm package for Pliny: https://www.npmjs.com/package/pliny. It doesn't have any documentation, I tried to pull the components of the npm package. It didn't workout ( without even throwing any error )

1- I will see if I should push those changes to https://github.com/datopian/portaljs/tree/main/packages/core/src 
2- Should I update the documentation ( open a PR ) for the multiple analytic in flowershow-app? https://github.com/datopian/flowershow-app/blob/main/content/docs/analytics.md

**Comment by mohamedsalem401** [comment]
I moved the components to `@portaljs/core` and updated the code.

**Pull request merged**
