### PR TITLE
Add user config type

### LINKED ISSUE #625: User config has no type
This makes it quite difficult to know what's supported when hosting Flowershow yourself.

### PR DESCRIPTION
**Pull request by homostellaris**
Adds a type for the user config which makes it easier to know what's possible when setting up your own Flowershow instance.

Closes #625

### CODE REVIEW

**Comment by mohamedsalem401** [comment]
@homostellaris 
Thanks a lot for this.🙌 I've reviewed and tested this. 

I think it's good to be merged.

**Comment by mohamedsalem401** [comment]
@homostellaris 
The only thing left would be to move this to the right repo, which is https://github.com/datopian/portaljs/blob/main/packages/core/src/config/default.ts, as I don't think those changes should be in Flowershow.

**Comment by homostellaris** [comment]
@mohamedsalem401 I don't think that would make sense as it's describing the flowers how config which is different to the portal config. You'll notice in siteConfig.ts that where appropriate the portal config types are being referenced but you can also see the additional properties that are specific to flowershow.

If you're worried about the failing build I think that's just due to some upstream changes that I need to include in the config.

**Comment by homostellaris** [comment]
@mohamedsalem401 the above commit should fix the build error in Vercel.

**Pull request merged**
