### PR TITLE
Support wiki links with spaces

### PR DESCRIPTION
**Pull request by FranciscoMoretti**
Added support for wiki links like the ones created when an image is pasted in obsidian:

Example:
```
![[Pasted image 20230425114940.png]]
```

Previously, this was reduced to "Pasted".

Note for reviewers: I haven't tested this change thoroughly, is there a reason why this might be problematic?

### CODE REVIEW

**Comment by rufuspollock** [comment]
@FranciscoMoretti awesome - we'll review!

**Comment by rufuspollock** [comment]
@FranciscoMoretti awesome - we'll review!

**Comment by rufuspollock** [comment]
@FranciscoMoretti awesome - we'll review!

**Comment by rufuspollock** [comment]
@FranciscoMoretti awesome - we'll review!

**Comment by rufuspollock** [comment]
@olayway can you take a look!

**Comment by olayway** [comment]
@FranciscoMoretti This has been fixed as part of larger refactoring lately. I'm closing this PR but thank you so much for reporting the issue and giving it a go solving it. I really appreciate it! 🌻

**Comment by FranciscoMoretti** [comment]
Glad to hear it was fixed. Thanks for following up on my contribution!

**Pull request closed without merging**
