### PR TITLE
Docs updates after switch to MarkdownDB

### LINKED ISSUE #484: Documentation updates
## User story

As a user, I want to be able to find comprehensive and up-to-date documentation of a given feature. Specifically after the switch from `contentlayer` to our `@flowershow/markdowndb` package.

## Acceptance
- [ ] all docs pages are up-to-date
- [ ] every feature has a doc page
- [ ] every doc page is listed on the `docs/index.md` page

## Tasks
- [ ] `docs/config` page has a full list of all available config options with a short description (if not super clear) 
- [ ] ...

### PR DESCRIPTION
**Pull request by olayway**
Closes #484 

## Changes
All docs pages reviewed and updated to be in line with current Flowershow version, which uses MarkdownDB.
Comprehensive list of changes in issue #484.

## TBD
Not sure what do we want to do with our blog posts. Should we update them as well (and e.g. add "updated" date to frontmatter) or archive and write new ones with focus on MarkdownDB?

### CODE REVIEW

**Comment by rufuspollock** [comment]
> Not sure what do we want to do with our blog posts. Should we update them as well (and e.g. add "updated" date to frontmatter) or archive and write new ones with focus on MarkdownDB?

Can you move this discussion into issue so we don't lose it. I think this is a separate discussion.

**Comment by rufuspollock** [comment]
@luccasmmg could you review - it's good practice to have an outsider check it!

**Review by luccasmmg — APPROVED** [review]
LGTM One question, Why isn't there a section explaining markdowndb the same way there was explaining the content layer? The last month I kinda of got curious about it but there wasn't any place besides the github discussions to figure it out, is there a plan to have documentation about it?

**Comment by olayway** [comment]
> LGTM One question, Why isn't there a section explaining markdowndb the same way there was explaining the content layer? The last month I kinda of got curious about it but there wasn't any place besides the github discussions to figure it out, is there a plan to have documentation about it?

@luccasmmg We do have some basic information in the MarkdownDB package itself. Probably we'll also write some blog post about the whole switch from Contentlayer to MarkdownDB but that's for another time I think.

**Pull request merged**
